void cycle_label (WINDOW *window);
void cycle_value (WINDOW *window, unsigned int value);
void data_labels (WINDOW *window);
void data_values (WINDOW *window, unsigned int *values);
void mode_label (WINDOW *window);
void mode_value (WINDOW *window, unsigned int value);
void pc_label (WINDOW *window);
void pc_value (WINDOW *window, unsigned int value);
void ram_labels (WINDOW *window, unsigned int scroll);
void ram_values (WINDOW *window, unsigned int *values, unsigned int scroll);
void registers_labels (WINDOW *window);
void registers_values (WINDOW *window, unsigned int *values);
void text_labels (WINDOW *window);
void text_values (WINDOW *window, unsigned int *values);
int kbhit ();
void refresh_windows (WINDOW *cycle_window, unsigned int cycle_count, WINDOW *data_window, unsigned int *data, WINDOW *mode_window, unsigned int mode, WINDOW *pc_window, unsigned int pc, WINDOW *ram_window, unsigned int *ram, unsigned int scroll, WINDOW *registers_window, unsigned int *registers, WINDOW *text_window, unsigned int *text);
